version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
        environment:
          DB_USERNAMNE: 'root'
          DB_PASSWORD: 'root123'
      - image: circleci/mysql:8.0.20-ram
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_USER: forge
          MYSQL_DATABASE: forge
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_PASSWORD: 'forge'
    steps:
      - checkout  
      - run:
          name: Install PHP extensions
          command: |
            sudo docker-php-ext-install pdo_mysql
            sudo docker-php-ext-enable pdo_mysql
      - restore_cache:
          key: composer-v1-{{ checksum "./app/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./app
      - save_cache:
          key: composer-v1-{{ checksum "./app/composer.lock" }}
          paths:
            - vendor
      - run: touch ./app/database/testing.sqlite
      - run: php app/artisan migrate --env=testing
      - run:
          name: php test
          command: app/vendor/bin/phpunit --configuration=./app/phpunit.xml

  deploy:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - add_ssh_keys
      - run:
          name: deploy
          command: |
            ssh -o StrictHostKeyChecking=no -t webkatu@${HOST_NAME} "cd ifthen_plan_app && \
              git pull origin main && \
              composer install -n --no-dev --prefer-dist && \
              npm ci && \
              npm run prod && \
              php artisan config:cache"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main