version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
      - image: circleci/postgres:11.6-alpine
        environment:
          POSTGRES_DB: larasns
          POSTGRES_USER: default
          POSTGRES_PASSWORD: secret
    environment:
      APP_ENV: testing
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: larasns
      DB_USERNAME: default
      DB_PASSWORD: secret
    steps:
      - checkout
      - run: sudo docker-php-ext-install pdo_sqlite
      - run: sudo docker-php-ext-enable pdo_sqlite
      - restore_cache:
          key: composer-v1-{{ checksum "./app/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./app
      - save_cache:
          key: composer-v1-{{ checksum "./app/composer.lock" }}
          paths:
            - vendor
      - run: touch ./app/storage/testing.sqlite
      - run: php app/artisan migrate --env=testing
      - run:
          name: php test
          command: app/vendor/bin/phpunit --configuration=./app/phpunit.xml
